repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        entry: black --check --diff --color -S
        language_version: python3 # Should be a command that runs python3.6+
        types_or: [python, pyi]
